declare const cregexs: {
   isEmail: () => RegExp;
   isEmpty: () => RegExp;
   isNoEmpty: () => RegExp;
   blacklist: <T = string>(chars?: T[]) => RegExp;
   isAscii: () => RegExp;
   isBIC: () => RegExp;
   isBase32: () => RegExp;
   isBase64: () => RegExp;
   isBoolean: () => RegExp;
   isCreditCard: () => RegExp;
   isFullWidth: () => RegExp;
   isHalfWidth: () => RegExp;
   isHash: (algorithm: string) => RegExp;
   isHexColor: () => RegExp;
   isHexadecimal: () => RegExp;
   isLength: (options: { min: number; max: number }) => RegExp;
   isLowercase: () => RegExp;
   isMacAddress: () => RegExp;
   isMacAddressNoColons: () => RegExp;
   isMacAddressWithHyphen: () => RegExp;
   isMacAddressWithSpaces: () => RegExp;
   isMD5: () => RegExp;
   isMagnetURI: () => RegExp;
   isMobilePhone: (locale: string) => RegExp;
   isMultibyte: () => RegExp;
   isNumeric: () => RegExp;
   isOctal: () => RegExp;
   isPort: () => RegExp;
   isPostalCode: (locale: string) => RegExp;
   isRFC3339: () => RegExp;
   isSlug: () => RegExp;
   isSurrogatePair: () => RegExp;
   isUrl: () => RegExp;
   isUUID: (version?: string | number) => RegExp;
   isUppercase: () => RegExp;
};

export default cregexs;
export { cregexs };
